export const products = [
    {
      id: 1,
      name: "Золотое кольцо с фианитом",
      image: "/images/ring1.jpg",
      price: 350,
      oldPrice: 1290,
      weight: "2.4 г",
      size: "16.5",
      assay: "585",
    },
    {
      id: 2,
      name: "Цепочка плетёная",
      image: "/images/chain1.jpg",
      price: 620,
      oldPrice: 2100,
      weight: "5.2 г",
      size: "45 см",
      assay: "585",
    },
    {
        id: 3,
        name: "Золотое кольцо с фианитом",
        image: "/images/ring1.jpg",
        price: 350,
        oldPrice: 1290,
        weight: "2.4 г",
        size: "16.5",
        assay: "585",
      },
      {
        id: 4,
        name: "Цепочка плетёная",
        image: "/images/chain1.jpg",
        price: 620,
        oldPrice: 2100,
        weight: "5.2 г",
        size: "45 см",
        assay: "585",
      },
      {
        id: 5,
        name: "Золотое кольцо с фианитом",
        image: "/images/ring1.jpg",
        price: 350,
        oldPrice: 1290,
        weight: "2.4 г",
        size: "16.5",
        assay: "585",
      },
      {
        id: 6,
        name: "Цепочка плетёная",
        image: "/images/chain1.jpg",
        price: 620,
        oldPrice: 2100,
        weight: "5.2 г",
        size: "45 см",
        assay: "585",
      },
      {
          id: 7,
          name: "Золотое кольцо с фианитом",
          image: "/images/ring1.jpg",
          price: 350,
          oldPrice: 1290,
          weight: "2.4 г",
          size: "16.5",
          assay: "585",
        },
        {
          id: 8,
          name: "Цепочка плетёная",
          image: "/images/chain1.jpg",
          price: 620,
          oldPrice: 2100,
          weight: "5.2 г",
          size: "45 см",
          assay: "585",
        },
  ];
  