import firstRing from '../images/product-images/firstRing.jpg';
import bracletDiamonds from '../images/product-images/braclet-diamonds-1.jpg';
import cepj1 from '../images/product-images/cepj-1.jpg';
import goldBraclet from '../images/product-images/gold-braclet-1.jpg';
import sergiDiamonds from '../images/product-images/sergi-diamond-1.png';
import ringDiamondSaphire from '../images/product-images/ring-diamond-saphire.jpg';
import diamondRing2 from '/Users/admin/Documents/GitHub/jewerly-shop/src/components/images/product-images/diamond-ring-2.jpg';
import bracletGribalde from '../images/product-images/braclet-gribalde-1.jpg';

export const products = [
    {
      id: 1,
      name: "Кольцо из белого золота с бриллиантами",
      image: firstRing,
      price: 13999,
      oldPrice: 149990,
      weight: "2.4 г",
      size: "",
      assay: "585",
      availableSizes: ['15', '16', '16.5', '17', '18'],
    },
    {
      id: 2,
      name: "Браслет с бриллиантами",
      image: bracletDiamonds,
      price: 18999,
      oldPrice: 44999,
      weight: "5.2 г",
      size: "45 см",
      assay: "585",
      availableSizes: ['17', '18', '19', '20', '21'],
    },
    {
        id: 3,
        name: "Цепь из белого золота",
        image: cepj1,
        price: 9999,
        oldPrice: 39999,
        weight: "2.4 г",
        size: "16.5",
        assay: "585",
        availableSizes: ['35', '40', '45', '50'],
      },
      {
        id: 4,
        name: "Браслет из желтого золота",
        image: goldBraclet,
        price: 11999,
        oldPrice: 72999,
        weight: "5.2 г",
        size: "45 см",
        assay: "585",
        availableSizes: ['17', '18', '19', '20', '21'],
      },
      {
        id: 5,
        name: "Золотые серьги с «танцующим» бриллиантом",
        image: sergiDiamonds,
        price: 11999,
        oldPrice: 99990,
        weight: "2.4 г",
        size: "16.5",
        assay: "585",
        availableSizes: ['1'],
      },
      {
        id: 6,
        name: "Кольцо с бриллиантами и сапфиром",
        image: ringDiamondSaphire,
        price: 8999,
        oldPrice: 54990,
        weight: "5.2 г",
        size: "45 см",
        assay: "585",
        availableSizes: ['16', '16.5', '17', '17.5', '19'],
      },
      {
        id: 7,
        name: "Обручальное кольцо MORZE из белого золота с бриллиантами",
        image: diamondRing2,
        price: 10999,
        oldPrice: 69999,
        weight: "2.4 г",
        size: "16.5",
        assay: "585",
        availableSizes: ['16', '16.5', '17', '17.5', '19'],
      },
      {
        id: 8,
        name: "Браслет, плетение Гарибальди",
        image: bracletGribalde,
        price: 13999,
        oldPrice: 99999,
        weight: "5.2 г",
        size: "45 см",
        assay: "585",
        availableSizes: ['17', '18', '19', '20', '21', '22'],
      },
      {
        id: 9,
        name: "Золотое кольцо с фианитом",
        image: "/images/ring1.jpg",
        price: 350,
        oldPrice: 1290,
        weight: "2.4 г",
        size: "16.5",
        assay: "585",
      },
      {
        id: 10,
        name: "Цепочка плетёная",
        image: "/images/chain1.jpg",
        price: 620,
        oldPrice: 2100,
        weight: "5.2 г",
        size: "45 см",
        assay: "585",
      },
      {
        id: 11,
        name: "Золотое кольцо с фианитом",
        image: "/images/ring1.jpg",
        price: 350,
        oldPrice: 1290,
        weight: "2.4 г",
        size: "16.5",
        assay: "585",
      },
      {
        id: 12,
        name: "Цепочка плетёная",
        image: "/images/chain1.jpg",
        price: 620,
        oldPrice: 2100,
        weight: "5.2 г",
        size: "45 см",
        assay: "585",
      },
  ];
  